use_default_settings: true

general:
  debug: true
  instance_name: "LocalSearxNG"

server:
  secret_key: "changeme"
  limiter: false

search:
  formats:
    - html
    - json
  safe_search: 0
  autocomplete: "duckduckgo"
  languages: [en]
  engines:
    - name: duckduckgo
      engine: duckduckgo
    - name: wikipedia
      engine: wikipedia

ui:
  static_path: ""
  default_locale: "en"

plugins: {}